// <auto-generated />
using System;
using MarcadorUdla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarcadorUdla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027014659_ConfigureNpgsqlTimestamp")]
    partial class ConfigureNpgsqlTimestamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarcadorUdla.Models.EventoPartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Datos")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Equipo")
                        .HasColumnType("text");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("MarcadorUdla.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("NumeroCamiseta")
                        .HasColumnType("integer");

                    b.Property<string>("Posicion")
                        .HasColumnType("text");

                    b.Property<int>("UniversidadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UniversidadId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("MarcadorUdla.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("JuezUsername")
                        .HasColumnType("text");

                    b.Property<int>("UniversidadLocalId")
                        .HasColumnType("integer");

                    b.Property<int>("UniversidadVisitanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UniversidadLocalId");

                    b.HasIndex("UniversidadVisitanteId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("MarcadorUdla.Models.SetPartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Finalizado")
                        .HasColumnType("boolean");

                    b.Property<string>("Ganador")
                        .HasColumnType("text");

                    b.Property<int>("NumeroSet")
                        .HasColumnType("integer");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.Property<int>("PuntosLocal")
                        .HasColumnType("integer");

                    b.Property<int>("PuntosVisitante")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("MarcadorUdla.Models.Universidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Universidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LogoUrl = "/logos/udla.png",
                            Nombre = "Universidad de Las Américas"
                        },
                        new
                        {
                            Id = 2,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LogoUrl = "/logos/central.png",
                            Nombre = "Universidad Central"
                        });
                });

            modelBuilder.Entity("MarcadorUdla.Models.EventoPartido", b =>
                {
                    b.HasOne("MarcadorUdla.Models.Partido", "Partido")
                        .WithMany("Eventos")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("MarcadorUdla.Models.Jugador", b =>
                {
                    b.HasOne("MarcadorUdla.Models.Universidad", "Universidad")
                        .WithMany("Jugadores")
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universidad");
                });

            modelBuilder.Entity("MarcadorUdla.Models.Partido", b =>
                {
                    b.HasOne("MarcadorUdla.Models.Universidad", "UniversidadLocal")
                        .WithMany("PartidosLocal")
                        .HasForeignKey("UniversidadLocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarcadorUdla.Models.Universidad", "UniversidadVisitante")
                        .WithMany("PartidosVisitante")
                        .HasForeignKey("UniversidadVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UniversidadLocal");

                    b.Navigation("UniversidadVisitante");
                });

            modelBuilder.Entity("MarcadorUdla.Models.SetPartido", b =>
                {
                    b.HasOne("MarcadorUdla.Models.Partido", "Partido")
                        .WithMany("Sets")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("MarcadorUdla.Models.Partido", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("MarcadorUdla.Models.Universidad", b =>
                {
                    b.Navigation("Jugadores");

                    b.Navigation("PartidosLocal");

                    b.Navigation("PartidosVisitante");
                });
#pragma warning restore 612, 618
        }
    }
}
